### ISSUE TITLE
数据输入问题

### ISSUE THREAD

**Issue by leiyaqi** [leexinhao/ZeroI2V#1]
你好，我对您的这项工作非常感兴趣，我仔细看了您的文章，在文章中你对多头注意力进行了拆分，让k个头关注空间信息的提取，n-k个头关注时间信息的提取，我好奇的是您使用的是图像模型，那么视频数据是如何输入的？

**Comment by leexinhao** [comment]
你可以参考[mmaction2](https://github.com/open-mmlab/mmaction2)框架的实现，我们的代码的数据输入和增强都是基于该框架实现的，基本只改动了模型部分。

**Comment by leiyaqi** [comment]
> 你可以参考[mmaction2](https://github.com/open-mmlab/mmaction2)框架的实现，我们的代码的数据输入和增强都是基于该框架实现的，基本只改动了模型部分。

好的，谢谢
