### ISSUE TITLE
Questions about the dimension of W_up and W_down

### ISSUE THREAD

**Issue by Yusics** [leexinhao/ZeroI2V#2]
Thanks for your great work, ZeroI2V! The idea is quite impressive. I just have a few quick questions about your linear adapter.

1.
You have mentioned in your paper: 
W_new = W_Adapter * W_old = (I + W_up * W_down)*W_old

So assume W_old's dimension is m * n
Your W_new is also m * n, is that correct?

Then in this case W_up should be m * k and W_down should k * m and W_Adapter is a square matrix here, is this correct?

2.
Why does LoRA require more tuning parameters comparing with linear adapter?

Really appreciate your help and your work! Thanks!

**Comment by leexinhao** [comment]
1. You're absolutely right.
2. In the same bottleneck, the parallel LoRA needs to fit $W_{m \times 4m}$, while the  linear adapter still only needs to fit $W_{m \times m}$, which causes more tuning parameters.

**Comment by Yusics** [comment]
Thanks for your prompt reply!

Sorry I may miss something for my second question. Given W_old is a m x n matrix. Linear Adapter required two matrices, W_up and W_down which has m x k and k x m dimension. So the additional tuning parameters are 2 x m x k.

For LoRA, W_up and W_down dimension are m x k and k x n, so the additional tuning parameters are (m + n) x k.
I'm not sure why is there a 4m?

Thanks!

**Comment by leexinhao** [comment]
Sorry for your confusion, for MLP in transformer, W_up^mlp are mx4m.

**Comment by Yusics** [comment]
Got it! Thanks for the prompt clarification!
