### ISSUE TITLE
Missing file.

### ISSUE THREAD

**Issue by TJQdoIt9527** [leexinhao/ZeroI2V#5]
Hello, the work you have done is very meaningful and I am very interested. But it seems that some training and testing scripts are missing, such as dist_test.sh, dist_train.sh, run_exp.sh.  If you have time, could you please add it? Thank you very much!

**Comment by leexinhao** [comment]
You could find them in https://github.com/open-mmlab/mmaction2/tree/main/tools

**Comment by TJQdoIt9527** [comment]
Thank you very much for your prompt reply. I have just found a similar solution. I apologize for taking up your valuable time.
