### ISSUE TITLE
Reproduce results: About the configuration file of HMDB/UCF

### ISSUE THREAD

**Issue by TJQdoIt9527** [leexinhao/ZeroI2V#6]
Hello, I apologize for disturbing you during the weekend, but the following issues have been a headache for me and I really need your help, thank you very much！

I have made some changes to the K400 configuration file you provided in order to reproduce the results on the hmdb dataset. But the results I obtained from the training and testing sets of the first two splits are as follows(VIT-B/16, clip_len=32,frame_interval=4,epoch=50):
Split1：acc/top1: 0.6804  acc/top5: 0.9229  acc/mean1: 0.6804  data_time: 0.0339  time: 1.3507
Split2：acc/top1: 0.6510  acc/top5: 0.9131  acc/mean1: 0.6510  data_time: 0.0055  time: 0.1720
The above results are far less than the results you reported（VIT-B/16 acc:73.7%）.

May I ask if there is anything special to note about the training configuration file for hmdb, or could you provide configuration files for the hmdb51/ucf101 datasets so that I can reproduce the results of hmdb and ucf in your paper. Thank you for your reply!

**Comment by leexinhao** [comment]
It's my train pipeline, which use uniformsample:
```python
train_pipeline = [
    dict(type='UniformSample', clip_len=32),
    dict(type='RawFrameDecode', io_backend='petrel'),
    dict(type='Resize', scale=(-1, 256)),
    dict(
        type='PytorchVideoWrapper',
        op='RandAugment',
        magnitude=7,
        num_layers=4),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='PackActionInputs')
]
```
And I only train for 40 epoch, you can modify it, I will update config soon.

**Comment by TJQdoIt9527** [comment]
Thank you for your prompt reply. I have achieved over 73% performance on the hmdb dataset using vit-B/16.
